using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Text.Json;
using System.Runtime.InteropServices;
using SkiaSharp;
static class Native { [DllImport("libSkiaSharp")]public static extern UIntPtr sk_region_write_to_memory(IntPtr r,IntPtr p); }
class Program {
 static object Rects(SKRegion r){var list=new List<int[]>();using var it=r.CreateRectIterator();while(it.Next(out var x))list.Add(new[]{x.Left,x.Top,x.Right,x.Bottom});return list;}
 static byte[] Memory(SKRegion r){var n=(int)Native.sk_region_write_to_memory(r.Handle,IntPtr.Zero);var p=Marshal.AllocHGlobal(n);try{Native.sk_region_write_to_memory(r.Handle,p);var b=new byte[n];Marshal.Copy(p,b,0,n);return b;}finally{Marshal.FreeHGlobal(p);}}
 static void Main(string[] args){var fontPath=args.Length>0?args[0]:Path.Combine("dist","fonts","DejaVuSans.ttf");var result=new Dictionary<string,object?>();using var region=new SKRegion();foreach(var r in new[]{new SKRectI(10,10,20,20),new SKRectI(30,10,40,20),new SKRectI(15,30,25,40)})region.Op(r,SKRegionOperation.Union);result["regionRects"]=Rects(region);try{result["regionBytes"]=Memory(region).Select(x=>(int)x).ToArray();}catch(Exception e){result["regionMemoryError"]=e.Message;}using var circle=new SKPath();circle.AddCircle(10,10,8);using var clip=new SKRegion(new SKRectI(0,0,20,20));using var circleRegion=new SKRegion();circleRegion.SetPath(circle,clip);result["circleRects"]=Rects(circleRegion);
 using var bitmap=new SKBitmap(1,1);using var canvas=new SKCanvas(bitmap);using var filter=SKColorFilter.CreateHighContrast(new SKHighContrastConfig(false,SKHighContrastConfigInvertStyle.InvertBrightness,0));using var paint=new SKPaint{Color=new SKColor(10,80,240,255),ColorFilter=filter};canvas.DrawPaint(paint);result["highContrast"]=new[]{(int)bitmap.GetPixel(0,0).Red,(int)bitmap.GetPixel(0,0).Green,(int)bitmap.GetPixel(0,0).Blue,(int)bitmap.GetPixel(0,0).Alpha};
 using var pth=new SKPath();pth.MoveTo(0,0);pth.CubicTo(0,100,100,100,100,0);pth.LineTo(150,0);pth.LineTo(150,80);using var corner=SKPathEffect.CreateCorner(12);using var stroke=new SKPaint{Style=SKPaintStyle.Stroke,StrokeWidth=3,PathEffect=corner};using var outPath=new SKPath();stroke.GetFillPath(pth,outPath);result["cornerSvg"]=outPath.ToSvgPathData();
 result["colors"]=Enumerable.Range(0,361).Where(x=>x%7==0).Select(h=>new{h,hsl=SKColor.FromHsl(h,57,43).ToString(),hsv=SKColor.FromHsv(h,57,43).ToString()}).ToArray();result["pmColors"]=Enumerable.Range(0,256).Select(a=>new{a,color=(uint)SKPMColor.PreMultiply(new SKColor(17,113,231,(byte)a)),roundtrip=SKPMColor.UnPreMultiply(SKPMColor.PreMultiply(new SKColor(17,113,231,(byte)a))).ToString()}).ToArray();result["transfer"]=new[]{("Srgb",SKColorSpaceTransferFn.Srgb),("TwoDotTwo",SKColorSpaceTransferFn.TwoDotTwo),("Linear",SKColorSpaceTransferFn.Linear),("Rec2020",SKColorSpaceTransferFn.Rec2020),("Pq",SKColorSpaceTransferFn.Pq),("Hlg",SKColorSpaceTransferFn.Hlg)}.Select(t=>new{name=t.Item1,values=t.Item2.Values,transforms=Enumerable.Range(0,21).Select(i=>t.Item2.Transform(i/20f)).ToArray(),inverse=t.Item2.Invert().Values}).ToArray();
 var colors=typeof(SKColors).GetFields(System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.Static).Where(f=>f.FieldType==typeof(SKColor)).ToDictionary(f=>f.Name,f=>((SKColor)f.GetValue(null)!).ToString());result["namedColors"]=colors;result["enums"]=typeof(SKColor).Assembly.GetExportedTypes().Where(t=>t.IsEnum).ToDictionary(t=>t.FullName!,t=>Enum.GetNames(t).ToDictionary(n=>n,n=>Convert.ToInt64(Enum.Parse(t,n))));
 using(var face=SKTypeface.FromFile(fontPath)){result["fonts"]=new[]{12f,32f}.Select(size=>{using var font=new SKFont(face,size);var metrics=font.Metrics;var glyphs=font.GetGlyphs("Hello Ω");var widths=font.GetGlyphWidths("Hello Ω",out var glyphBounds);return new{size,metrics=typeof(SKFontMetrics).GetProperties().ToDictionary(p=>p.Name,p=>p.GetValue(metrics)),glyphs,widths,bounds=glyphBounds.Select(r=>new[]{r.Left,r.Top,r.Right,r.Bottom}).ToArray()};}).ToArray();}
 result["runtimeDeclarations"]=typeof(SKColor).Assembly.GetExportedTypes().OrderBy(t=>t.FullName).Select(t=>new{type=t.FullName,members=t.GetMembers(System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.DeclaredOnly).Select(m=>new{name=m.Name,kind=m.MemberType.ToString(),signature=m.ToString()}).ToArray()}).ToArray();
using(var face=SKTypeface.FromFile(fontPath))using(var shaper=new SkiaSharp.HarfBuzz.SKShaper(face)){
result["shaping"]=new[]{"office affine ffi","مرحبا بالعالم","A\u0308 + e\u0301","AVATAR Ω 😀"}.Select(text=>{using var font=new SKFont(face,32,1.25f);var r=shaper.Shape(text,3,5,font);return new{text,codepoints=r.Codepoints,clusters=r.Clusters,points=r.Points.Select(p=>new[]{p.X,p.Y}),width=r.Width};}).ToArray();}
result["fontStyleClamp"]=new[]{new[]{-4,-4,-4},new[]{1111,22,3},new[]{550,5,1}}.Select(v=>{using var f=new SKFontStyle(v[0],v[1],(SKFontStyleSlant)v[2]);return new{input=v,output=new[]{f.Weight,f.Width,(int)f.Slant}};}).ToArray();
result["hbAssembly"]=typeof(HarfBuzzSharp.Buffer).Assembly.FullName;
result["assembly"]=typeof(SKColor).Assembly.FullName;Console.WriteLine(JsonSerializer.Serialize(result,new JsonSerializerOptions{WriteIndented=true,NumberHandling=System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals}));}
}
