import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {execFileSync,spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const installedRoot=fileURLToPath(new URL('../',import.meta.url));
const site=process.env.SKIA_SOURCE_ROOT||installedRoot;
const {createDocuments}=await import(existsSync(fileURLToPath(new URL('./documents.js',import.meta.url)))?'./documents.js':site+'/dist/lib/documents.js');
const pdfCli=['pdfinfo','pdftotext','pdftoppm'].every(cmd=>!spawnSync(cmd,['-v']).error);
const python=spawnSync('python3',['-c','import zipfile,xml.etree.ElementTree']).status===0;
const mupdf=spawnSync('python3',['-c','import fitz']).status===0;
const {Initialize}=await import(site+'/dist/lib/index.js');
const require=createRequire(import.meta.url),K=await require(site+'/dist/vendor/canvaskit.cjs')({locateFile:n=>site+'/dist/vendor/'+n});
const api=await Initialize({CanvasKit:K,isolated:true,fonts:[{family:'DejaVu Sans',data:readFileSync(site+'/dist/fonts/DejaVuSans.ttf')}]});
if(existsSync(fileURLToPath(new URL('./documents.js',import.meta.url)))||!('RasterFallbacks' in api.SKDocument.prototype))Object.assign(api,createDocuments(K,api));
const {SKDocument,SKPaint,SKColors,SKColor,SKRect,SKPath,SKFont,SKTypeface,SKShader,SKPoint,SKImage,SKImageInfo,SKDynamicMemoryWStream}=api;
const output=fileURLToPath(new URL('./test-output/',import.meta.url));mkdirSync(output,{recursive:true});
function managedPdf(stream=null,metadata={}){if(stream&&!stream.Write&&!stream.write)return SKDocument.CreatePdf({...stream,NativeBackend:false});return SKDocument.CreatePdf(stream,{...metadata,NativeBackend:false});}
function scene(doc){const c=doc.BeginPage(400,300);c.Clear(SKColors.White);const p=new SKPaint({IsAntialias:true,Color:SKColor.Parse('#186aee')});c.DrawRect(20,20,100,60,p);c.Save();c.Translate(140,25);c.RotateDegrees(12);c.ClipRect(new SKRect(0,0,100,80));c.DrawCircle(45,45,40,p);c.Restore();const path=new SKPath().MoveTo(20,120).QuadTo(70,70,120,120).CubicTo(160,170,220,70,260,120).Close();p.Color=SKColor.Parse('#33a67a');c.DrawPath(path,p);path.Dispose();const gradient=SKShader.CreateLinearGradient(new SKPoint(20,160),new SKPoint(220,160),[SKColors.Red,SKColors.Blue]);p.Shader=gradient;gradient.Dispose();c.DrawRect(20,160,200,30,p);p.Shader=null;p.Color=SKColors.Black;const face=SKTypeface.Default,font=new SKFont(face,20);face.Dispose();c.DrawText('Skia Web — Zażółć gęślą jaźń',20,230,font,p);font.Dispose();const pixels=Uint8Array.from([255,0,0,255,0,255,0,255,0,0,255,255,255,255,0,255]),im=SKImage.FromPixels(new SKImageInfo(2,2,K.ColorType.RGBA_8888,K.AlphaType.Unpremul),pixels);c.DrawImage(im,new SKRect(310,160,370,220));im.Dispose();p.Dispose();doc.EndPage();return doc;}
test('vector PDF exports shapes, gradient, embedded fonts, searchable Unicode and images',{skip:!(pdfCli)},()=>{const out=new SKDynamicMemoryWStream(),doc=scene(managedPdf(out,{Title:'Vector graphics — żółć'}));const data=doc.ToData(),s=new TextDecoder('latin1').decode(data.AsSpan());assert.equal(doc.IsRasterDocument,false);assert.equal(doc.RasterFallbacks.length,0);assert.match(s,/\/Subtype \/Type0/);assert.match(s,/\/CIDToGIDMap/);assert.match(s,/\/ToUnicode/);assert.match(s,/\/ShadingType 2/);assert.match(s,/ W|W n/);assert.equal(data.Size,out.BytesWritten);writeFileSync(output+'vector.pdf',data.AsSpan());const text=execFileSync('pdftotext',[output+'vector.pdf','-'],{encoding:'utf8'});assert.match(text,/Skia Web — Zażółć gęślą jaźń/);const info=execFileSync('pdfinfo',[output+'vector.pdf'],{encoding:'utf8'});assert.match(info,/Pages:\s+1/);execFileSync('pdftoppm',['-png','-scale-to','700','-singlefile',output+'vector.pdf',output+'vector']);data.Dispose();out.Dispose();doc.Dispose();});
test('XPS is a valid OPC package with vector paths, searchable Glyphs and font/image resources',{skip:!(python)},()=>{const doc=scene(SKDocument.CreateXps({Title:'Vector XPS'})),data=doc.ToData();writeFileSync(output+'vector.xps',data.AsSpan());assert.equal(doc.RasterFallbacks.length,0);const result=execFileSync('python3',['-c',`import zipfile,xml.etree.ElementTree as E
p='${output}vector.xps'
with zipfile.ZipFile(p) as z:
 assert z.testzip() is None
 for n in z.namelist():
  if n.endswith(('.xml','.rels','.fdseq','.fdoc','.fpage')): E.fromstring(z.read(n))
 page=E.fromstring(z.read('Documents/1/Pages/1.fpage'))
 ns={'x':'http://schemas.microsoft.com/xps/2005/06'}
 assert len(page.findall('.//x:Path',ns))>=4
 glyphs=page.findall('.//x:Glyphs',ns)
 assert ''.join(g.attrib.get('UnicodeString','') for g in glyphs)=='Skia Web — Zażółć gęślą jaźń'
 fonts=[n for n in z.namelist() if n.endswith('.odttf')]
 assert len(fonts)==1
 name=fonts[0].split('/')[-1].split('.')[0]
 key=bytes.fromhex(name.replace('-',''))
 font=bytearray(z.read(fonts[0]))
 for i in range(32): font[i]^=key[15-i%16]
 assert font[:4]==bytes([0,1,0,0])
 assert any(n.endswith('.png') for n in z.namelist())
 print('OPC XML, searchable Glyphs, deobfuscated SFNT and resource images verified')`],{encoding:'utf8'});assert.match(result,/verified/);data.Dispose();doc.Dispose();});
test('unsupported image effect creates bounded raster patch, preserving vector text',{skip:!(pdfCli)},()=>{const doc=managedPdf(),c=doc.BeginPage(400,300),p=new SKPaint({Color:SKColors.Red}),filter=api.SKImageFilter.CreateBlur(3,3);p.ImageFilter=filter;filter.Dispose();c.DrawCircle(90,90,30,p);p.ImageFilter=null;p.Color=SKColors.Black;const f=new SKFont(null,18);c.DrawText('Searchable after blur',20,240,f,p);doc.Close();assert.equal(doc.RasterFallbacks.length,1);assert.match(doc.RasterFallbacks[0].Reason,/paint effect/);assert(doc.RasterFallbacks[0].PixelWidth<800);assert(doc.RasterFallbacks[0].PixelHeight<600);const d=doc.ToData();writeFileSync(output+'filtered.pdf',d.AsSpan());assert.match(execFileSync('pdftotext',[output+'filtered.pdf','-'],{encoding:'utf8'}),/Searchable after blur/);d.Dispose();doc.Dispose();p.Dispose();f.Dispose();});
test('multiple pages, canvas invalidation, write stream and abort lifecycle',()=>{const doc=managedPdf(),c=doc.BeginPage(100,100);c.DrawRect(10,10,20,20,new SKPaint());doc.EndPage();assert(c.IsDisposed);assert.throws(()=>c.DrawRect(0,0,1,1,new SKPaint()),/disposed/i);doc.BeginPage(120,80);doc.Close();assert.equal(doc.PageCount,2);assert.throws(()=>doc.BeginPage(1,1),/closed/);doc.Dispose();const aborted=SKDocument.CreateXps();aborted.BeginPage(10,10);aborted.Abort();assert.equal(aborted.PageCount,0);aborted.Dispose();});
test('save-layer alpha composite remains vector and restores subsequent vector output',()=>{const doc=managedPdf(),c=doc.BeginPage(200,200),p=new SKPaint({Color:SKColors.Red}),layer=new SKPaint({Color:new SKColor(255,255,255,100)});c.SaveLayer(layer);c.DrawCircle(60,60,30,p);c.Restore();c.DrawRect(120,120,30,30,p);doc.Close();assert.equal(doc.RasterFallbacks.length,0);assert.equal(doc._pages[0].commands[0].kind,'layer');assert.equal(doc._pages[0].commands.at(-1).kind,'path');p.Dispose();layer.Dispose();doc.Dispose();});
test('complex-script shaping exports positioned vector glyphs and logical searchable text',{skip:!(pdfCli&&mupdf)},()=>{for(const format of ['pdf','xps']){const doc=format==='pdf'?managedPdf():SKDocument.CreateXps(),c=doc.BeginPage(420,130),p=new SKPaint({Color:SKColors.Black}),f=new SKFont(null,26);c.DrawShapedText('office — مرحبا بالعالم',20,60,f,p);const d=doc.ToData();assert.equal(doc.RasterFallbacks.length,0,JSON.stringify(doc.RasterFallbacks));writeFileSync(output+'shaped.'+format,d.AsSpan());if(format==='pdf'){const text=execFileSync('pdftotext',[output+'shaped.pdf','-'],{encoding:'utf8'});assert.match(text,/office/);assert(text.includes('مرحبا')||text.includes('ابحرم'));execFileSync('pdftoppm',['-png','-scale-to','800','-singlefile',output+'shaped.pdf',output+'shaped']);}else{const check=execFileSync('python3',['-c',`import fitz
f=fitz.open('${output}shaped.xps')
print(f[0].get_text())
f[0].get_pixmap().save('${output}shaped-xps.png')`],{encoding:'utf8'});assert.match(check,/o(?:ff)?ice/);assert.match(execFileSync('python3',['-c',`import zipfile
with zipfile.ZipFile('${output}shaped.xps') as z: print(z.read('Documents/1/Pages/1.fpage').decode())`],{encoding:'utf8'}),/UnicodeString="ffi" Indices="\(3:1\)5044/);}d.Dispose();p.Dispose();f.Dispose();doc.Dispose();}});
test('CID-keyed static CFF OpenType embeddings preserve glyph IDs in PDF and XPS',{skip:!(pdfCli&&mupdf)},()=>{const fixture=readFileSync(new URL('./fixtures/RobotoFlex-Black.otf',import.meta.url)),face=SKTypeface.FromData(fixture),font=new SKFont(face,30);face.Dispose();for(const format of ['pdf','xps']){const doc=format==='pdf'?managedPdf():SKDocument.CreateXps(),c=doc.BeginPage(360,100),p=new SKPaint({Color:SKColors.Black});c.DrawText('Variable CFF: AVW 900',15,55,font,p);const d=doc.ToData();writeFileSync(output+'cff.'+format,d.AsSpan());assert.equal(doc.RasterFallbacks.length,0);if(format==='pdf'){assert.match(execFileSync('pdftotext',[output+'cff.pdf','-'],{encoding:'utf8'}),/Variable CFF: AVW 900/);const result=execFileSync('pdftoppm',['-png','-scale-to','700','-singlefile',output+'cff.pdf',output+'cff'],{encoding:'utf8'});assert.equal(result,'');}else{const result=execFileSync('python3',['-c',`import fitz
f=fitz.open('${output}cff.xps');print(f[0].get_text());f[0].get_pixmap().save('${output}cff-xps.png')`],{encoding:'utf8'});assert.match(result,/Variable CFF: AVW 900/);}d.Dispose();doc.Dispose();p.Dispose();}font.Dispose();});
test('text blobs and rich paragraphs retain vector searchable content',{skip:!(pdfCli)},()=>{const doc=managedPdf(),c=doc.BeginPage(360,180),p=new SKPaint({Color:SKColors.Black}),f=new SKFont(null,20),blob=api.SKTextBlob.Create('Vector text blob',f);c.DrawTextBlob(blob,15,35,p);blob.Dispose();f.Dispose();const builder=new api.SKParagraphBuilder({TextStyle:{FontFamilies:['DejaVu Sans'],FontSize:18,Color:SKColors.Red}});builder.AddText('Searchable rich paragraph');const paragraph=builder.Build();builder.Dispose();paragraph.Layout(320);c.DrawParagraph(paragraph,15,65);paragraph.Dispose();const data=doc.ToData();writeFileSync(output+'paragraph.pdf',data.AsSpan());const extracted=execFileSync('pdftotext',[output+'paragraph.pdf','-'],{encoding:'utf8'});assert.match(extracted,/Vector text blob/);assert.match(extracted,/Searchable rich paragraph/);assert.equal(doc.RasterFallbacks.length,0);data.Dispose();doc.Dispose();p.Dispose();});
test('explicit native drawing callback records bounded animation/effect patches in PDF and XPS',()=>{for(const format of ['pdf','xps']){const doc=format==='pdf'?managedPdf():SKDocument.CreateXps(),c=doc.BeginPage(120,100),p=new SKPaint({Color:SKColors.Red});assert.equal(c._isDocumentCanvas,true);const result=c.DrawNative(target=>{assert.equal(target.DrawNative,undefined);target._native.drawRect([12,15,40,60],p._native);return 42;},'Skottie animation');assert.equal(result,42);const d=doc.ToData();assert.equal(doc.RasterFallbacks.length,1);assert.equal(doc.RasterFallbacks[0].Operation,'DrawNative');assert.equal(doc.RasterFallbacks[0].Reason,'Skottie animation');assert(doc.RasterFallbacks[0].PixelWidth<240);assert(doc._pages[0].commands.some(q=>q.rasterPatch));writeFileSync(output+'native.'+format,d.AsSpan());d.Dispose();p.Dispose();doc.Dispose();}});

function compareVectors(name,draw,{formats=['pdf','xps'],tolerance=3}={}){
  const reference=api.SKSurface.Create(new SKImageInfo(640,360)),rc=reference.Canvas;rc.Scale(2,2);rc.Clear(SKColors.White);draw(rc);const image=reference.Snapshot(),png=image.Encode('Png');writeFileSync(output+name+'-reference.png',png.AsSpan());png.Dispose();image.Dispose();reference.Dispose();
  for(const format of formats){const doc=format==='pdf'?managedPdf({StrictVector:true}):SKDocument.CreateXps({StrictVector:true}),c=doc.BeginPage(320,180);c.Clear(SKColors.White);draw(c);const data=doc.ToData();assert.equal(doc.RasterFallbacks.length,0);writeFileSync(output+name+'.'+format,data.AsSpan());const r=JSON.parse(execFileSync('python3',['-c',`import fitz,json
from PIL import Image,ImageChops,ImageStat
p=fitz.open('${output+name}.${format}');pix=p[0].get_pixmap(matrix=fitz.Matrix(2,2),alpha=False);actual=Image.frombytes('RGB',(pix.width,pix.height),pix.samples);actual.save('${output+name}-${format}.png');expected=Image.open('${output+name}-reference.png').convert('RGB');assert abs(expected.width-actual.width)<=1 and abs(expected.height-actual.height)<=1,(expected.size,actual.size);box=(0,0,min(expected.width,actual.width),min(expected.height,actual.height));expected=expected.crop(box);actual=actual.crop(box);stat=ImageStat.Stat(ImageChops.difference(expected,actual));print(json.dumps({'mean':sum(stat.mean)/3,'maximum':max(x[1] for x in stat.extrema)}))`],{encoding:'utf8'}));assert(r.mean<tolerance,format+' pixel MAE '+r.mean+' exceeds '+tolerance);data.Dispose();doc.Dispose();}
}
test('strict vector documents reject unrepresentable operations before changing drawing state',()=>{for(const format of ['pdf','xps']){const doc=format==='pdf'?managedPdf({StrictVector:true}):SKDocument.CreateXps({StrictVector:true}),c=doc.BeginPage(100,100),p=new SKPaint({Color:SKColors.Red}),f=api.SKImageFilter.CreateBlur(2,2);p.ImageFilter=f;f.Dispose();assert.throws(()=>c.DrawCircle(20,20,10,p),/Strict vector.*paint effect/);assert.equal(doc.RasterFallbacks.length,0);assert.equal(doc._page.commands.length,0);assert.throws(()=>c.DrawNative(()=>{}),/Strict vector/);p.ImageFilter=null;c.DrawRect(10,10,20,20,p);doc.Close();assert.equal(doc._pages[0].commands.length,1);p.Dispose();doc.Dispose();}});
test('isolated nested alpha layers are vector groups with correct overlap compositing',()=>{compareVectors('vector-layers',c=>{const p=new SKPaint({Color:SKColors.Blue}),layer=new SKPaint({Color:new SKColor(255,255,255,100)});c.DrawRect(10,10,240,145,p);c.SaveLayer(layer);p.Color=SKColors.Red;c.DrawRect(25,25,160,85,p);p.Color=SKColors.Green;c.DrawRect(90,70,180,70,p);c.SaveLayer(layer);p.Color=SKColors.Yellow;c.DrawCircle(210,75,35,p);c.Restore();c.Restore();layer.Dispose();p.Dispose();},{tolerance:2});});
test('transformed mirrored translucent gradients and stroked gradient outlines match independent renderers',()=>{compareVectors('vector-gradients',c=>{const p=new SKPaint({Color:SKColors.White}),g=SKShader.CreateLinearGradient(new SKPoint(0,0),new SKPoint(40,10),[SKColors.Red,new SKColor(20,120,255,50),SKColors.Green],[0,.4,1],api.SKShaderTileMode.Mirror,api.SKMatrix.CreateTranslation(20,5));p.Shader=g;g.Dispose();c.DrawRect(10,10,290,65,p);p.Style=api.SKPaintStyle.Stroke;p.StrokeWidth=12;c.DrawRoundRect(new SKRect(30,105,280,160),20,20,p);p.Dispose();},{tolerance:3});});
test('picture replay keeps vector commands after recorder inputs are disposed',()=>{const rec=new api.SKPictureRecorder(),c=rec.BeginRecording(new SKRect(0,0,220,120)),p=new SKPaint({Color:SKColors.Red}),f=new SKFont(null,22);c.DrawRect(0,0,200,60,p);p.Color=SKColors.Black;c.DrawText('Vector picture żółć',8,36,f,p);const picture=rec.EndRecording();p.Dispose();f.Dispose();rec.Dispose();compareVectors('vector-picture',c=>{c.Save();c.Translate(30,30);c.RotateDegrees(9);c.DrawPicture(picture);c.Restore();},{tolerance:2});for(const format of ['pdf','xps']){const text=format==='pdf'?execFileSync('pdftotext',[output+'vector-picture.pdf','-'],{encoding:'utf8'}):execFileSync('python3',['-c',`import fitz;print(fitz.open('${output}vector-picture.xps')[0].get_text())`],{encoding:'utf8'});assert.equal(text.replace(/\s/g,''),'Vectorpictureżółć');}picture.Dispose();});
test('rich paragraph colors, backgrounds, and shaped runs remain searchable vectors',()=>{const builder=new api.SKParagraphBuilder({TextStyle:{FontFamilies:['DejaVu Sans'],FontSize:22,Color:SKColors.Red}});builder.AddText('Red office ');builder.PushStyle({Color:SKColors.Blue,BackgroundColor:SKColors.Yellow,FontSize:26});builder.AddText('blue ffi');builder.Pop();builder.AddText(' żółć');const paragraph=builder.Build();builder.Dispose();paragraph.Layout(280);compareVectors('vector-rich',c=>c.DrawParagraph(paragraph,15,25),{tolerance:3});paragraph.Dispose();});
test('rotation-scale glyph blobs retain glyph vectors and searchable unicode',()=>{const f=new SKFont(null,24),text='Skia żółć',tr=Array.from(text,(_,i)=>({SCos:Math.cos(i*.06),SSin:Math.sin(i*.06),Tx:i*24,Ty:Math.sin(i*.2)*15})),blob=api.SKTextBlob.CreateRotationScale(text,f,tr);f.Dispose();const p=new SKPaint({Color:SKColors.Black});compareVectors('vector-rotated',c=>c.DrawTextBlob(blob,20,80,p),{tolerance:2});blob.Dispose();p.Dispose();});
test('font subsetting preserves composite accents and reduces embedded font size',()=>{let compact,full;for(const subset of [true,false]){const doc=managedPdf({SubsetFonts:subset,StrictVector:true}),c=doc.BeginPage(320,180),p=new SKPaint({Color:SKColors.Black}),f=new SKFont(null,28);c.DrawText('Zażółć Ąęé ffi',15,55,f,p);const data=doc.ToData();writeFileSync(output+'subset-'+subset+'.pdf',data.AsSpan());if(subset)compact=data.Size;else full=data.Size;assert.match(execFileSync('pdftotext',[output+'subset-'+subset+'.pdf','-'],{encoding:'utf8'}),/Zażółć Ąęé ffi/);execFileSync('pdftoppm',['-png','-scale-to','500','-singlefile',output+'subset-'+subset+'.pdf',output+'subset-'+subset]);data.Dispose();p.Dispose();f.Dispose();doc.Dispose();}assert(compact<full*.5,compact+' versus '+full);});
test('conical circle gradients remain vector in PDF and compatible XPS focus geometry',()=>{compareVectors('vector-conical',c=>{const p=new SKPaint({Color:SKColors.White}),g=SKShader.CreateTwoPointConicalGradient(new SKPoint(140,80),12,new SKPoint(160,90),70,[SKColors.Yellow,SKColors.Blue],[0,1],api.SKShaderTileMode.Clamp);p.Shader=g;g.Dispose();c.DrawRect(10,10,290,150,p);p.Dispose();},{tolerance:2});});
test('decal gradients remain transparent outside their end stops',()=>{compareVectors('vector-decal',c=>{const p=new SKPaint({Color:SKColors.White}),g=SKShader.CreateLinearGradient(new SKPoint(80,0),new SKPoint(200,0),[SKColors.Red,SKColors.Blue],[0,1],api.SKShaderTileMode.Decal);p.Shader=g;g.Dispose();c.DrawRect(10,10,290,150,p);p.Dispose();},{tolerance:2});});
test('gradient and outlined text exports real glyph geometry plus searchable text',()=>{compareVectors('vector-glyph-paint',c=>{const p=new SKPaint({Color:SKColors.White,IsAntialias:true}),g=SKShader.CreateLinearGradient(new SKPoint(20,0),new SKPoint(250,0),[SKColors.Red,SKColors.Blue]),f=new SKFont(null,32);p.Shader=g;g.Dispose();c.DrawText('Gradient żółć',18,60,f,p);p.Shader=null;p.Color=SKColors.Black;p.Style=api.SKPaintStyle.Stroke;p.StrokeWidth=1.5;c.DrawText('Outline ffi',18,120,f,p);f.Dispose();p.Dispose();},{tolerance:2});assert.match(execFileSync('pdftotext',[output+'vector-glyph-paint.pdf','-'],{encoding:'utf8'}),/Gradient żółć/);});
test('strict vector recording permits large pages without a large raster allocation',()=>{const doc=managedPdf({StrictVector:true}),c=doc.BeginPage(100000,100000),p=new SKPaint({Color:SKColors.Red});c.DrawRect(10,10,30,40,p);const data=doc.ToData();assert(data.Size<10000);assert.equal(doc.RasterFallbacks.length,0);data.Dispose();p.Dispose();doc.Dispose();});
test('PDF metadata and XPS options preserve struct defaults, equality and declared constants',()=>{const Metadata=api.SKDocumentPdfMetadata,Options=api.SKDocumentXpsOptions;assert.equal(SKDocument.DefaultRasterDpi,72);assert.equal(new Metadata().RasterDpi,0);assert.equal(new Metadata().EncodingQuality,0);assert.equal(Metadata.Default.RasterDpi,72);assert.equal(Metadata.Default.EncodingQuality,101);assert.equal(new Metadata(85).EncodingQuality,85);assert.equal(new Metadata(72.5).RasterDpi,72.5);assert.equal(new Metadata(144,90).RasterDpi,144);assert.equal(Metadata.FromRasterDpi(144).EncodingQuality,101);const a=Metadata.Default,b=Metadata.Default;a.Title=b.Title='Metadata title';a.Creation=new Date('2025-01-02T03:04:05Z');b.Creation=new Date('2025-01-02T03:04:05Z');assert(a.Equals(b));assert.equal(a.GetHashCode(),b.GetHashCode());b.Title='Other';assert(!a.Equals(b));const o=new Options();assert.equal(o.Dpi,0);assert.equal(o.AllowNoPngs,false);assert(o.Equals(new Options()));const doc=managedPdf({...a,Producer:'Custom producer'});doc.BeginPage(100,100);const data=doc.ToData();writeFileSync(output+'metadata.pdf',data.AsSpan());const info=execFileSync('pdfinfo',[output+'metadata.pdf'],{encoding:'utf8'});assert.match(info,/Metadata title/);assert.match(info,/Custom producer/);assert.match(info,/Jan\s+2.*2025/);data.Dispose();doc.Dispose();});
test('managed PDF annotations preserve URLs and named destinations without raster patches',()=>{const doc=managedPdf({StrictVector:true}),c=doc.BeginPage(200,100);c.DrawUrlAnnotation(new SKRect(10,10,90,30),'https://example.org/graphics');c.DrawNamedDestination(new SKPoint(20,50),'chapter-one');c.DrawLinkDestinationAnnotation(new SKRect(100,10,190,30),'chapter-one');const data=doc.ToData();writeFileSync(output+'annotations.pdf',data.AsSpan());const annotations=JSON.parse(execFileSync('python3',['-c',`import fitz,json
p=fitz.open('${output}annotations.pdf');print(json.dumps(p[0].get_links(),default=str))`],{encoding:'utf8'}));assert(annotations.some(a=>a.uri==='https://example.org/graphics'));assert(annotations.some(a=>a.page===0||a.nameddest==='chapter-one'));assert.equal(doc.RasterFallbacks.length,0);data.Dispose();doc.Dispose();});
test('filename document overloads flush owned streams into the mounted file system',()=>{assert(api.SKFileWStream);for(const format of ['pdf','xps']){const path='/documents/export.'+format,doc=format==='pdf'?SKDocument.CreatePdf(path,{NativeBackend:false}):SKDocument.CreateXps(path,{Dpi:96});doc.BeginPage(30,40);doc.Close();const data=api.SKFileSystem.ReadAllBytes(path);assert(data.length>100);assert.equal(new TextDecoder().decode(data.subarray(0,format==='pdf'?4:2)),format==='pdf'?'%PDF':'PK');doc.Dispose();}});
test('repeated image draws share one encoded resource across pages',()=>{const im=SKImage.FromPixels(new SKImageInfo(2,2,K.ColorType.RGBA_8888,K.AlphaType.Unpremul),Uint8Array.from([255,0,0,255,0,255,0,255,0,0,255,255,255,255,0,255]));for(const format of ['pdf','xps']){const doc=format==='pdf'?managedPdf({StrictVector:true}):SKDocument.CreateXps({StrictVector:true});for(let page=0;page<3;page++){const c=doc.BeginPage(100,100);for(let i=0;i<30;i++)c.DrawImage(im,(i%10)*8,Math.floor(i/10)*8);doc.EndPage();}const data=doc.ToData();if(format==='pdf')assert.equal((new TextDecoder('latin1').decode(data.AsSpan()).match(/\/Subtype \/Image/g)??[]).length,1);else{writeFileSync(output+'deduplicated.xps',data.AsSpan());assert.equal(execFileSync('python3',['-c',`import zipfile;z=zipfile.ZipFile('${output}deduplicated.xps');print(len([n for n in z.namelist() if n.endswith('.png')]))`],{encoding:'utf8'}).trim(),'1');}data.Dispose();doc.Dispose();}im.Dispose();});
test('XPS package declares named link targets and cross-page navigation',()=>{const doc=SKDocument.CreateXps({StrictVector:true}),a=doc.BeginPage(200,100);a.DrawLinkDestinationAnnotation(new SKRect(10,10,90,30),'chapter-two');doc.EndPage();const b=doc.BeginPage(200,100);b.DrawNamedDestination(new SKPoint(20,30),'chapter-two');b.DrawUrlAnnotation(new SKRect(10,50,150,80),'https://example.org/graphics');const data=doc.ToData();writeFileSync(output+'annotations.xps',data.AsSpan());const xml=execFileSync('python3',['-c',`import zipfile,xml.etree.ElementTree as E
z=zipfile.ZipFile('${output}annotations.xps');ns={'x':'http://schemas.microsoft.com/xps/2005/06'};root=E.fromstring(z.read('Documents/1/FixedDocument.fdoc'));assert len(root.findall('.//x:LinkTarget',ns))==1;p=z.read('Documents/1/Pages/1.fpage').decode();assert '/Documents/1/Pages/2.fpage#d' in p;assert 'FixedPage.NavigateUri' in p;print('cross-page XPS target declared')`],{encoding:'utf8'});assert.match(xml,/declared/);data.Dispose();doc.Dispose();});
