import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const installed=fileURLToPath(new URL('../',import.meta.url)),site=process.env.SKIA_SOURCE_ROOT||installed,engine=process.env.SKIA_ENGINE_ROOT||site+'/dist/vendor',require=createRequire(import.meta.url);
const K=await require(engine+'/canvaskit.cjs')({locateFile:n=>engine+'/'+n});
const {Initialize}=await import(site+'/dist/lib/index.js'),S=await Initialize({CanvasKit:K,isolated:true,fonts:[{family:'DejaVu Sans',data:readFileSync(site+'/dist/fonts/DejaVuSans.ttf')}]});
if(existsSync(fileURLToPath(new URL('./documents.js',import.meta.url)))){const {createDocuments}=await import('./documents.js');Object.assign(S,createDocuments(K,S));}
const output=fileURLToPath(new URL('./test-output/',import.meta.url));mkdirSync(output,{recursive:true});
test('bundled native PDF writer renders filters, pictures, paragraphs and searchable fonts',()=>{assert.equal(typeof K._SkiaSharpDocument,'function');const doc=S.SKDocument.CreatePdf({Title:'Native PDF — żółć',Author:'SkiaSharp Web',RasterDpi:144});assert.equal(doc.Backend,'NativeSkia');const observable=typeof doc._nativeDocument.rasterDiagnostics==='function';assert.equal(doc.RasterFallbackReporting,observable?'NativeDecisionSites':'UnavailableNative');assert.deepEqual(doc.RasterFallbacks,observable?[]:null);const c=doc.BeginPage(400,240),p=new S.SKPaint({Color:S.SKColors.Blue,IsAntialias:true}),f=new S.SKFont(null,24);c.Clear(S.SKColors.White);c.DrawText('Native PDF — searchable żółć',20,40,f,p);const fx=S.SKImageFilter.CreateBlur(5,5);p.ImageFilter=fx;fx.Dispose();c.DrawCircle(70,110,35,p);p.ImageFilter=null;const recorder=new S.SKPictureRecorder(),pc=recorder.BeginRecording(new S.SKRect(0,0,80,60));pc.DrawRect(0,0,80,60,p);const picture=recorder.EndRecording();c.DrawPicture(picture,160,80);picture.Dispose();recorder.Dispose();const builder=new S.SKParagraphBuilder({TextStyle:{FontFamilies:['DejaVu Sans'],FontSize:20,Color:S.SKColors.Black}});builder.AddText('Native office ffi paragraph');const paragraph=builder.Build();builder.Dispose();paragraph.Layout(350);c.DrawParagraph(paragraph,20,185);paragraph.Dispose();doc.EndPage();const data=doc.ToData();writeFileSync(output+'native-backend.pdf',data.AsSpan());const info=execFileSync('pdfinfo',[output+'native-backend.pdf'],{encoding:'utf8'}),text=execFileSync('pdftotext',[output+'native-backend.pdf','-'],{encoding:'utf8'});assert.match(info,/Native PDF — żółć/);assert.match(text,/Native PDF — searchable żółć/);assert.match(text.normalize('NFKC'),/Native office ffi paragraph/);if(observable)assert(doc.RasterDiagnostics.Total>0);execFileSync('pdftoppm',['-png','-scale-to','800','-singlefile',output+'native-backend.pdf',output+'native-backend']);data.Dispose();doc.Dispose();p.Dispose();f.Dispose();});
test('explicit JavaScript and StrictVector policies select audited vector capture over the native writer',()=>{for(const options of [{NativeBackend:false},{Backend:'JavaScript'},{StrictVector:true}]){const doc=S.SKDocument.CreatePdf(options);assert.equal(doc.Backend,'VectorJavaScript');assert.deepEqual(doc.RasterFallbacks,[]);doc.BeginPage(10,10);const data=doc.ToData();assert(data.Size>100);data.Dispose();doc.Dispose();}});
test('native PDF metadata carries UTC dates, producer and PDF/A output intent',()=>{const doc=S.SKDocument.CreatePdf({Title:'Native archive',Producer:'Document conformance test',Creation:new Date('2025-01-02T03:04:05Z'),Modified:new Date('2025-02-03T04:05:06Z'),PdfA:true}),c=doc.BeginPage(200,100),p=new S.SKPaint({Color:S.SKColors.Black}),font=new S.SKFont(null,20);c.DrawText('Archive text',10,40,font,p);const data=doc.ToData();writeFileSync(output+'native-pdfa.pdf',data.AsSpan());const info=execFileSync('pdfinfo',[output+'native-pdfa.pdf'],{encoding:'utf8'}),metadata=execFileSync('pdfinfo',['-meta',output+'native-pdfa.pdf'],{encoding:'utf8'});assert.match(info,/Document conformance test/);assert.match(info,/Jan\s+2.*2025/);assert.match(info,/Feb\s+3.*2025/);assert.match(metadata,/pdfaid:part>2</);assert.match(metadata,/pdfaid:conformance>B</);assert(new TextDecoder('latin1').decode(data.AsSpan()).includes('/OutputIntents'));assert.match(execFileSync('pdftotext',[output+'native-pdfa.pdf','-'],{encoding:'utf8'}),/Archive text/);data.Dispose();p.Dispose();font.Dispose();doc.Dispose();});
test('native SVG canvas writes vector paths and explicitly outlined fonts to a borrowed stream',()=>{const stream=new S.SKDynamicMemoryWStream(),canvas=S.SKSvgCanvas.Create(new S.SKRect(10,20,210,120),stream,S.SKSvgCanvasFlags.ConvertTextToPaths),paint=new S.SKPaint({Color:S.SKColors.Blue}),font=new S.SKFont(null,18);canvas.DrawRect(20,30,80,50,paint);canvas.DrawText('Outlined SVG',20,100,font,paint);canvas.Dispose();assert.equal(stream.IsDisposed,false);const data=stream.DetachAsData();writeFileSync(output+'native-vector.svg',data.AsSpan());const result=execFileSync('python3',['-c',`import xml.etree.ElementTree as E,fitz
p='${output}native-vector.svg';r=E.parse(p).getroot();ns={'s':'http://www.w3.org/2000/svg'};assert len(r.findall('.//s:path',ns))>0;assert len(r.findall('.//s:text',ns))==0;assert len(r.findall('.//s:image',ns))==0;doc=fitz.open(p);pix=doc[0].get_pixmap();pix.save('${output}native-vector-svg.png');assert pix.pixel(20,20)[:3]==(0,0,255);print('vector paths parsed and rasterized')`],{encoding:'utf8'});assert.match(result,/parsed and rasterized/);assert.throws(()=>canvas.DrawRect(0,0,1,1,paint),/disposed/);data.Dispose();stream.Dispose();font.Dispose();paint.Dispose();});
