import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';import {createCore} from '../dist/lib/core.js';import {createPaths} from '../dist/lib/paths.js';import {createFonts} from '../dist/lib/fonts.js';import {ReadFont} from '../dist/lib/font-engine.js';
const require=createRequire(import.meta.url),K=await require('../dist/vendor/canvaskit.cjs')({wasmBinary:fs.readFileSync(new URL('../dist/vendor/canvaskit.wasm',import.meta.url))});const S=createCore(K);Object.assign(S,createPaths(K,S),createFonts(K,S));
const fixture=name=>new Uint8Array(fs.readFileSync(new URL('./fixtures/'+name,import.meta.url)));
const raster=(face,size,text='H')=>{const font=new K.Font(face._native,size),paint=new K.Paint(),surface=K.MakeSurface(120,100);font.setHinting(K.FontHinting.Full);font.setSubpixel(false);font.setEdging(K.FontEdging.Alias);paint.setColor(K.BLACK);surface.getCanvas().clear(K.WHITE);surface.getCanvas().drawText(text,3,80,paint,font);surface.flush();const image=surface.makeImageSnapshot();try{return new Uint8Array(image.readPixels(0,0,{width:120,height:100,colorType:K.ColorType.RGBA_8888,alphaType:K.AlphaType.Unpremul,colorSpace:K.ColorSpace.SRGB}));}finally{image.delete();font.delete();surface.delete();paint.delete();}};
for(const weight of [100,500,900])test(`hint fidelity: variable CFF2 at ${weight} retains hints and matches independent native/CFF1 reference pixels`,()=>{const source=S.SKTypeface.FromData(fixture('HintVariable.otf')),face=source.Clone({VariationDesignPosition:{wght:weight}}),reference=S.SKTypeface.FromData(fixture(`HintStatic-${weight}.otf`)),document=S.SKTypeface.FromData(face.GetDocumentFontData()),referenceDocument=S.SKTypeface.FromData(fixture(`HintReference-${weight}.otf`));assert.equal(face.FontFormat,'CFF2');assert.equal(document.FontFormat,'CFF');assert.equal(face.GetTableSize('fvar'),0);for(const size of [7,9,11,13,18,32,60]){assert.deepEqual(raster(face,size),raster(reference,size),`native hint pixels at ${size}px`);assert.deepEqual(raster(document,size),raster(referenceDocument,size),`document hint pixels at ${size}px`);assert.deepEqual(raster(face,size),raster(document,size),`native/document pixels at ${size}px`);}for(const f of [source,face,reference,document,referenceDocument])f.Dispose();});
test('hint fidelity: subroutines, mask bytes and long operand batches preserve independent native pixels',()=>{const source=S.SKTypeface.FromData(fixture('HintSubroutines.otf')),document=S.SKTypeface.FromData(source.GetDocumentFontData()),reference=S.SKTypeface.FromData(fixture('HintSubroutines-Reference.otf'));assert.ok(document);for(const text of ['H','W'])for(const size of [9,13,31,60])assert.deepEqual(raster(document,size,text),raster(source,size,text),text+' '+size);for(const size of [9,13,31,60])assert.deepEqual(raster(document,size),raster(reference,size));source.Dispose();document.Dispose();reference.Dispose();});
test('font records: canonical fields, value equality, palette overloads, axes and span counts',()=>{const axis=new S.SKFontVariationAxis('wght',100,400,900,true),copy=new S.SKFontVariationAxis(axis);assert.ok(axis.Equals(copy));assert.equal(axis.GetHashCode(),copy.GetHashCode());assert.equal(axis.TagName,'wght');const coordinate=new S.SKFontVariationPositionCoordinate('wght',700);assert.ok(coordinate.Equals(new S.SKFontVariationPositionCoordinate(coordinate)));const args=new S.SKFontArguments({VariationDesignPosition:[coordinate],PaletteIndex:1,PaletteOverrides:[{Index:0,Color:0xff112233}]});assert.equal(args.PaletteIndex,1);assert.equal(args.PaletteOverrides[0].Index,0);args.PaletteIndex=0;assert.equal(args.PaletteOverrides.length,1);const palette=new S.SKFontPaletteOverride(0,0xff112233);assert.ok(palette.Equals(args.PaletteOverrides[0]));const face=S.SKTypeface.FromData(fixture('HintVariable.otf'));assert.equal(face.VariationDesignParameterCount,1);const destination=[null];assert.equal(face.GetVariationDesignParameters(destination),1);assert.equal(destination[0].TagName,'wght');assert.equal(face.GetVariationDesignPosition(destination),1);assert.equal(destination[0].Value,100);assert.throws(()=>face.GetVariationDesignParameters([]),RangeError);const clone=face.Clone([coordinate]);assert.equal(clone.VariationDesignPosition[0].Value,700);clone.Dispose();face.Dispose();});
test('font cache: repeated instancing avoids HarfBuzz and caller buffer mutation cannot alter cached fonts',()=>{S.SKFontCache.Clear();const bytes=fixture('HintVariable.otf'),original=bytes.slice(),a=S.SKTypeface.FromData(bytes),b=S.SKTypeface.FromData(original);bytes.fill(0);const stats=S.SKFontCache.GetStatistics();assert.ok(stats.SourceHits>0);const first=a.Clone({VariationDesignPosition:{wght:750}}),before=S.SKFontCache.GetStatistics(),second=b.Clone({VariationDesignPosition:{wght:750}}),after=S.SKFontCache.GetStatistics();assert.equal(after.InstanceMisses,before.InstanceMisses);assert.equal(after.InstanceHits,before.InstanceHits+1);const exported=first.OpenStream();exported.fill(0);assert.deepEqual(raster(first,23),raster(second,23));const owner=first.Clone();assert.equal(owner.UniqueId,first.UniqueId);first.Dispose();assert.ok(owner.GetGlyph(72));owner.Dispose();second.Dispose();a.Dispose();b.Dispose();S.SKFontCache.MaxBytes=0;assert.equal(S.SKFontCache.GetStatistics().RetainedBytes,0);S.SKFontCache.MaxBytes=32*1024*1024;});
test('font manager caches preserve ownership, registration invalidation and empty style set behavior',()=>{const empty=new S.SKFontStyleSet();assert.equal(empty.Count,0);assert.deepEqual([...empty.GetEnumerator()],[]);empty.Dispose();const manager=new S.SKFontManager(),first=manager.RegisterFont(fixture('HintVariable.otf'),'Hints');first.Dispose();const a=manager.MatchFamily('hints'),b=manager.MatchFamily('HINTS');assert.equal(a.UniqueId,b.UniqueId);a.Dispose();assert.ok(b.GetGlyph(72));assert.equal(manager.FontFamilyCount,1);const registered=manager.RegisterFont(fixture('CFF-Regular.otf'),'Alternate');registered.Dispose();assert.equal(manager.FontFamilyCount,2);b.Dispose();manager.Dispose();});

test('font manager: numeric style overloads and registered BCP47 language priority select correct owned faces',()=>{const manager=new S.SKFontManager();manager.RegisterFont(fixture('HintStatic-100.otf'),'Latin',{Languages:['en']}).Dispose();manager.RegisterFont(fixture('HintStatic-900.otf'),'Polish',{Languages:['pl']}).Dispose();const pl=manager.MatchCharacter(null,400,5,S.SKFontStyleSlant.Upright,['en','pl-PL'],72);assert.equal(pl.FamilyName,'Polish');const en=manager.MatchCharacter(null,['pl','en-GB'],72);assert.equal(en.FamilyName,'Latin');const preferred=manager.MatchCharacter('LATIN',S.SKFontStyle.Normal,['pl'],72);assert.equal(preferred.FamilyName,'Latin');manager.Dispose();assert.ok(pl.ContainsGlyph(72));pl.Dispose();en.Dispose();preferred.Dispose();});
test('font cache: eviction releases cached native owners while active typefaces remain valid',()=>{const face=S.SKTypeface.FromData(fixture('HintVariable.otf')),clone=face.Clone({VariationDesignPosition:{wght:650}}),snapshot=raster(clone,17);S.SKFontCache.Clear();assert.equal(S.SKFontCache.GetStatistics().EntryCount,0);assert.deepEqual(raster(clone,17),snapshot);const copy=clone.Clone();clone.Dispose();assert.deepEqual(raster(copy,17),snapshot);copy.Dispose();face.Dispose();});

test('document font data always exposes SFNT rather than a WOFF container',()=>{const compressed=S.SKTypeface.FromData(fixture('ColorFixture.woff')),bytes=compressed.GetDocumentFontData(),signature=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(0);assert.equal(signature,0x00010000);const decoded=S.SKTypeface.FromData(bytes);assert.deepEqual([...decoded.GetTableData('CPAL')],[...compressed.GetTableData('CPAL')]);decoded.Dispose();compressed.Dispose();});

test('hint fidelity fixture actually distinguishes retained hint instructions from stripped outlines',()=>{const hinted=S.SKTypeface.FromData(fixture('HintStatic-100.otf')),stripped=S.SKTypeface.FromData(fixture('HintWithoutHints.otf'));let differences=0;for(const size of [7,9,11,13,18,32,60])if(Buffer.compare(raster(hinted,size),raster(stripped,size)))differences++;assert.ok(differences>0,'fixture must detect lost hints in actual native pixels');hinted.Dispose();stripped.Dispose();});
