import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';import{createRequire}from'node:module';import{createCore}from'../dist/lib/core.js';import{createPaths}from'../dist/lib/paths.js';import{createFonts}from'../dist/lib/fonts.js';
const require=createRequire(import.meta.url),K=await require('../dist/vendor/canvaskit.cjs')({wasmBinary:fs.readFileSync(new URL('../dist/vendor/canvaskit.wasm',import.meta.url))}),S=createCore(K);Object.assign(S,createPaths(K,S),createFonts(K,S));
const bytes=new Uint8Array(fs.readFileSync(new URL('../dist/fonts/DejaVuSans.ttf',import.meta.url))),reference=JSON.parse(fs.readFileSync(new URL('./fixtures/font-dotnet-reference.json',import.meta.url))),face=S.SKTypeface.FromData(bytes);
test('native fonts: all metric fields, glyph IDs, advances and bounds match independent .NET SkiaSharp',()=>{assert.equal(createHash('sha256').update(bytes).digest('hex'),reference.FontSha256);assert.equal(typeof K.SkiaSharpFontGetMetrics,'function');for(const sample of reference.Samples){const font=new S.SKFont(face,sample.size),metrics=font.Metrics,glyphs=font.GetGlyphs(reference.Text);for(const[name,expected]of Object.entries(sample.metrics)){if(expected===null)assert.equal(metrics[name],null);else assert.ok(Math.abs(metrics[name]-expected)<1e-5,`${name} at ${sample.size}: ${metrics[name]} != ${expected}`);}assert.deepEqual([...glyphs],sample.glyphs);assert.deepEqual([...font.GetGlyphWidths(glyphs)],sample.widths);assert.deepEqual(font.GetGlyphBounds(glyphs).map(r=>[r.Left,r.Top,r.Right,r.Bottom]),sample.bounds);font.Dispose();}});
test('native fonts: ForceAutoHinting and BaselineSnap change actual SkFont flags',()=>{const font=new S.SKFont(face,12);for(const value of [true,false,true]){font.ForceAutoHinting=value;assert.equal(K.SkiaSharpFontGetForceAutoHinting(font._native),value);assert.equal(font.ForceAutoHinting,value);font.BaselineSnap=value;assert.equal(K.SkiaSharpFontGetBaselineSnap(font._native),value);assert.equal(font.BaselineSnap,value);}font.Dispose();assert.throws(()=>font.ForceAutoHinting,/disposed/);});
test('native fonts: typeface Empty remains empty in fonts and has stable owned copies',()=>{const empty=S.SKTypeface.Empty;assert.ok(empty.IsEmpty);assert.equal(empty.GlyphCount,0);assert.equal(empty.GetGlyph(65),0);const clone=empty.Clone();assert.equal(clone.UniqueId,empty.UniqueId);empty.Dispose();assert.ok(clone.IsEmpty);const font=new S.SKFont(clone,12);assert.deepEqual([...font.GetGlyphs('Hello')],[0,0,0,0,0]);font.Dispose();clone.Dispose();});
test('native fonts: native provider fallback shapes a missing family glyph using registered fonts',()=>{assert.equal(typeof K.SkiaSharpMakeFontProvider,'function');const manager=new S.SKFontManager(),hint=new Uint8Array(fs.readFileSync(new URL('./fixtures/HintStatic-100.otf',import.meta.url)));manager.RegisterFont(hint,'Hints').Dispose();const fallback=manager.RegisterFont(bytes,'Fallback');const native=K.SkiaSharpFontMatchCharacter(manager._native,'Hints',400,5,0,[],0x3a9);assert.ok(native);assert.equal(K.SkiaSharpTypefaceUniqueID(native),fallback.UniqueId);native.delete();const builder=new S.SKParagraphBuilder({TextStyle:{FontFamilies:['Hints'],FontSize:24}},manager);builder.AddText('HΩ');const paragraph=builder.Build();paragraph.Layout(300);const glyphs=paragraph.GetShapedLines().flatMap(line=>line.runs.flatMap(run=>[...run.glyphs]));assert.ok(glyphs.includes(fallback.GetGlyph(0x3a9)));assert.ok(!glyphs.includes(0));paragraph.Dispose();builder.Dispose();fallback.Dispose();manager.Dispose();});
process.on('exit',()=>{face.Dispose();S.SKFontCache.Clear();});
test('native fonts: registered BCP47 metadata honors last language preference and primary-language matches',()=>{assert.equal(typeof K.SkiaSharpFontProviderSetLanguages,'function');const manager=new S.SKFontManager(),fixture=name=>new Uint8Array(fs.readFileSync(new URL('./fixtures/'+name,import.meta.url))),english=manager.RegisterFont(fixture('HintStatic-100.otf'),'English',{Languages:['en']}),polish=manager.RegisterFont(fixture('HintStatic-900.otf'),'Polish',{Languages:['pl']});for(const [languages,expected]of [[['en','pl-PL'],polish],[['pl','en-GB'],english]]){const native=K.SkiaSharpFontMatchCharacter(manager._native,'',400,5,0,languages,72);assert.ok(native);assert.equal(K.SkiaSharpTypefaceUniqueID(native),expected.UniqueId);native.delete();}const preferred=K.SkiaSharpFontMatchCharacter(manager._native,'English',400,5,0,['pl'],72);assert.equal(K.SkiaSharpTypefaceUniqueID(preferred),english.UniqueId);preferred.delete();english.Dispose();polish.Dispose();manager.Dispose();});
