import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createImages} from '../dist/lib/images.js';
import {createCore} from '../dist/lib/core.js';
const require=createRequire(import.meta.url);
const init=require('../dist/vendor/canvaskit.cjs');
const K=await init({locateFile:n=>fileURLToPath(new URL('../dist/vendor/'+n,import.meta.url))});
const core=createCore(K);
const {SKObject,SKImageInfo,SKColor,SKRect}=core;
Object.assign(core,createImages(K,core));
const {SKData,SKMemoryStream,SKDynamicMemoryWStream,SKBitmap,SKImage,SKPixmap,SKCodec,SKColorSpace,SKVertices}=core;
let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS',name);};
const rgba=c=>[c.Red,c.Green,c.Blue,c.Alpha];
test('data copies, bounded streams, and detaching writable buffers',()=>{const original=Uint8Array.of(1,2,3),data=SKData.CreateCopy(original);original[0]=8;assert.equal(data.AsSpan()[0],1);const stream=data.AsStream();assert.equal(stream.ReadByte(),1);assert.deepEqual([...stream.Peek(2)],[2,3]);assert.deepEqual([...stream.ReadToEnd()],[2,3]);assert(stream.IsAtEnd);assert(stream.Rewind());const out=new SKDynamicMemoryWStream();out.Write(data);out.WriteByte(4);const result=out.DetachAsData();assert.deepEqual([...result.AsSpan()],[1,2,3,4]);assert.equal(out.BytesWritten,0);[data,stream,out,result].forEach(x=>x.Dispose());assert.throws(()=>data.AsSpan(),/disposed/);});
test('mutable bitmap draw, exact RGBA read/write, subset, resize and resource ownership',()=>{const bitmap=new SKBitmap(8,8);bitmap.Erase(new SKColor(255,0,0));assert.deepEqual(rgba(bitmap.GetPixel(4,4)),[255,0,0,255]);bitmap.SetPixel(2,3,new SKColor(0,255,0));assert.deepEqual(rgba(bitmap.GetPixel(2,3)),[0,255,0,255]);const image=SKImage.FromBitmap(bitmap);bitmap.SetPixel(2,3,new SKColor(0,0,255));const pixels=image.ReadPixels();assert.deepEqual([...pixels.subarray((3*8+2)*4,(3*8+2)*4+4)],[0,255,0,255]);const subset=image.Subset(new SKRect(1,2,4,5));assert.equal(subset.Width,3);assert.equal(subset.Height,3);const resized=image.Resize(new SKImageInfo(16,16),'None');assert.equal(resized.Width,16);const copy=bitmap.Copy();bitmap.Dispose();assert.deepEqual(rgba(copy.GetPixel(2,3)),[0,0,255,255]);[image,subset,resized,copy].forEach(x=>x.Dispose());});
test('native PNG JPEG and WebP encode/decode round trips',()=>{const b=new SKBitmap(10,6);b.Erase(new SKColor(20,80,180));for(const format of ['Png','Jpeg','Webp']){const data=b.Encode(format,100);assert(data.Size>10);const decoded=SKBitmap.Decode(data);assert.equal(decoded.Width,10);assert.equal(decoded.Height,6);const pixel=decoded.GetPixel(4,3);assert(Math.abs(pixel.Red-20)<5);assert(Math.abs(pixel.Green-80)<5);assert(Math.abs(pixel.Blue-180)<5);const codec=SKCodec.Create(data);assert.equal(codec.EncodedFormat,format);assert.equal(codec.FrameCount,1);codec.Dispose();decoded.Dispose();data.Dispose();}assert.throws(()=>b.Encode('Gif'),/Unsupported/);b.Dispose();});
test('padded row bytes and borrowed pixmap updates',()=>{const b=new SKBitmap();b.AllocPixels(new SKImageInfo(3,2),16);b.Erase(new SKColor(0,0,0));const p=b.PeekPixels();const bytes=p.GetPixels();bytes.set([255,0,0,255],16+4);b.NotifyPixelsChanged();assert.deepEqual(rgba(b.GetPixel(1,1)),[255,0,0,255]);const img=SKImage.FromPixels(p);assert.equal(img.Width,3);const target=new SKBitmap(6,4);assert(b.ScalePixels(target,'None'));assert.deepEqual(rgba(target.GetPixel(2,2)),[255,0,0,255]);img.Dispose();target.Dispose();b.Dispose();assert.throws(()=>p.GetPixels(),/disposed/);p.Dispose();});
test('color spaces and indexed triangle vertices',()=>{const a=SKColorSpace.CreateSrgb(),b=SKColorSpace.CreateDisplayP3();assert(a.IsSrgb);assert(!b.IsSrgb);assert(!SKColorSpace.Equal(a,b));const v=SKVertices.CreateCopy('Triangles',[0,0,10,0,0,10],null,[new SKColor(255,0,0),new SKColor(0,255,0),new SKColor(0,0,255)],[0,1,2]);assert.equal(v.Bounds.Right,10);assert(v.UniqueId>0);v.Dispose();a.Dispose();b.Dispose();assert.throws(()=>SKColorSpace.CreateIcc(new Uint8Array()),/not exposed/);});
test('animated GIF frame selection and durations',()=>{const bytes=Uint8Array.from(Buffer.from('R0lGODlhAQABAIEAAP8AAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQACgAAACwAAAAAAQABAAAIBAABBAQAIfkEABQAAAAsAAAAAAEAAQCBAAD/AAAAAAAAAAAACAQAAQQEADs=','base64'));const c=SKCodec.Create(bytes);assert(c);assert.equal(c.FrameCount,2);assert.deepEqual(c.FrameInfo.map(x=>x.Duration),[100,200]);const f0=c.GetImage(0),f1=c.GetImage(1),again=c.GetImage(0);assert.deepEqual([...f0.ReadPixels()],[255,0,0,255]);assert.deepEqual([...f1.ReadPixels()],[0,0,255,255]);assert.deepEqual([...again.ReadPixels()],[255,0,0,255]);[f0,f1,again,c].forEach(x=>x.Dispose());});
test('image shaders own pixels independently and native vertex strips draw',()=>{const b=new SKBitmap(2,2);b.Erase(new SKColor(10,20,30));const image=SKImage.FromBitmap(b),shader=image.ToShader(core.SKShaderTileMode.Repeat,core.SKShaderTileMode.Repeat,core.SKSamplingOptions.Default);image.Dispose();b.Dispose();const target=new SKBitmap(8,8),paint=new core.SKPaint();paint.Shader=shader;target._surface.getCanvas().drawRect([0,0,8,8],paint._native);assert.deepEqual(rgba(target.GetPixel(6,6)),[10,20,30,255]);shader.Dispose();paint.Dispose();target.Dispose();const strip=SKVertices.CreateCopy(core.SKVertexMode.TriangleStrip,[0,0,10,0,0,10,10,10]);assert.equal(strip.Bounds.Bottom,10);strip.Dispose();});
test('RGBA float pixels and invalid resource accesses',()=>{const pixels=new Float32Array([1,0,.5,1]),image=SKImage.FromPixels(new SKImageInfo(1,1,K.ColorType.RGBA_F32,K.AlphaType.Unpremul),pixels);assert(image);const bytes=image.ReadPixels();assert.deepEqual([...bytes],[255,0,128,255]);const sourceInfo=new SKImageInfo(1,1,K.ColorType.RGBA_F32,K.AlphaType.Unpremul),readback=image.ReadPixels(sourceInfo);assert.deepEqual([...new Float32Array(readback.buffer)],[1,0,.5,1]);image.Dispose();assert.throws(()=>image.Width,/disposed/);});


core.SKCanvas=class extends SKObject{constructor(native,owner){super(native,false);this._owner=owner;}Clear(color){this._native.clear(color.ToFloatArray());}DrawRect(rect,paint){this._native.drawRect(rect.ToArray(),paint._native);}};
test('multipage lossless raster PDF with Unicode metadata and point-to-pixel scaling',()=>{const out=new SKDynamicMemoryWStream(),doc=core.SKDocument.CreatePdf(out,{Title:'Grafika – żółć',RasterDpi:144});const p=doc.BeginPage(72,36);p.Clear(new SKColor(255,255,255));const paint=new core.SKPaint({Color:new SKColor(255,0,0)});p.DrawRect(new SKRect(0,0,36,36),paint);doc.EndPage();assert(p.IsDisposed);doc.BeginPage(36,72).Clear(new SKColor(0,0,255));doc.Close();assert.equal(doc.PageCount,2);const data=doc.ToData();const bytes=data.AsSpan();assert.equal(new TextDecoder().decode(bytes.subarray(0,8)),'%PDF-1.4');assert.equal(out.BytesWritten,data.Size);data.Dispose();paint.Dispose();doc.Dispose();out.Dispose();});
console.log(`${checks} image integration checks passed.`);
