import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire}from'node:module';
import {pathToFileURL,fileURLToPath}from'node:url';
const base=process.env.SKIA_TEST_ROOT??fileURLToPath(new URL('../',import.meta.url));
const {Initialize}=await import(pathToFileURL(process.env.SKIA_INIT_MODULE??base+'/dist/lib/index.js'));
const {installOverloads}=await import(pathToFileURL(process.env.SKIA_OVERLOAD_MODULE??base+'/dist/lib/overloads.js'));
const req=createRequire(import.meta.url),K=await req(base+'/dist/vendor/canvaskit.cjs')({wasmBinary:fs.readFileSync(base+'/dist/vendor/canvaskit.wasm')});
const S=await Initialize({CanvasKit:K,fonts:false,isolated:true});installOverloads(K,S);
S.SKFontManager.Default.RegisterFont(fs.readFileSync(base+'/dist/fonts/DejaVuSans.ttf'),'DejaVu Sans').Dispose();
const surface=()=>S.SKSurface.Create(new S.SKImageInfo(160,120));
const pixel=(s,x,y)=>{const i=s.Snapshot();try{return Array.from(i.ReadPixels().slice((y*s.Width+x)*4,(y*s.Width+x)*4+4));}finally{i.Dispose();}};
const close=(a,b,e=1e-5)=>assert.ok(Math.abs(a-b)<e,`${a} ≈ ${b}`);
test('matrix44 sixteen-value constructor, properties, determinant, inverse, arrays and 3D projections',()=>{
 const m=new S.SKMatrix44(2,0,0,0,0,3,0,0,0,0,4,0,5,7,11,1);assert.equal(m.M30,5);assert.equal(m.Determinant(),24);assert.ok(m.MapPoint(1,2,3).Equals(new S.SKPoint3(7,13,23)));const inv=new S.SKMatrix44();assert.equal(m.TryInvert(inv),true);close(inv.MapPoint(m.MapPoint(1,2,3)).X,1);S.SKMatrix44.Concat(m,inv).Values.forEach((v,i)=>close(v,i%5===0?1:0));assert.deepEqual(m.ToRowMajor(new Float32Array(16)),Float32Array.from(m.Values));assert.deepEqual(S.SKMatrix44.FromColumnMajor(m.ToColumnMajor()).Values,m.Values);assert.deepEqual(m.PreConcat(S.SKMatrix44.Identity).Values,m.Values);assert.equal(m.M30,5);assert.equal(m.Transpose().M03,5);assert.equal(m.M30,5);assert.equal(S.SKMatrix44.Empty.TryInvert().Success,false);assert.equal(S.SKMatrix44.Empty.Invert().IsIdentity,false);const p=S.SKMatrix44.CreateScale(2,3,4,5,6,7);assert.deepEqual(p.MapPoint(5,6,7).ToArray(),[5,6,7]);
});
test('matrix output buffers, rotation-scale anchored mapping, rounded-rectangle transforms',()=>{
 const m=S.SKMatrix.CreateTranslation(5,7),out=new S.SKMatrix();assert.equal(m.TryInvert(out),true);assert.deepEqual(out.MapPoint(5,7).ToArray(),[0,0]);const dst=[];m.MapPoints(dst,[new S.SKPoint(1,2)]);assert.deepEqual(dst[0].ToArray(),[6,9]);const rs=S.SKRotationScaleMatrix.CreateDegrees(2,90,40,50,3,4);const q=rs.ToMatrix().MapPoint(3,4);close(q.X,40);close(q.Y,50);assert.deepEqual(rs.ToArray(),[rs.SCos,rs.SSin,rs.TX,rs.TY]);
 const rr=new S.SKRoundRect(S.SKRect.Create(0,0,100,60),10,20);const copy=new S.SKRoundRect(rr);assert.ok(copy.Rect.Equals(rr.Rect));assert.equal(copy.Type,S.SKRoundRectType.Simple);copy.Deflate(3,4);assert.equal(copy.GetRadii(0).X,7);const rotated=rr.Transform(S.SKMatrix.CreateRotationDegrees(90));assert.ok(rotated);close(rotated.GetRadii(0).X,20);close(rotated.Width,60);assert.equal(rr.TryTransform(S.SKMatrix.CreateSkew(.2,.4)).Success,false);
});
test('canvas pivot scale, point skew, picture coordinates, surface and color overloads render correct pixels',()=>{
 const s=surface(),p=new S.SKPaint({Color:S.SKColors.Red});try{const c=s.Canvas;c.Clear(S.SKColors.White);c.Save();c.Scale(2,2,10,10);c.DrawRect(10,10,10,10,p);c.Restore();assert.deepEqual(pixel(s,25,25),[255,0,0,255]);assert.deepEqual(pixel(s,5,5),[255,255,255,255]);c.DrawPoint(new S.SKPoint(5,5),S.SKColors.Blue);assert.equal(pixel(s,5,5)[2],255);c.Skew(new S.SKPoint(0,0));const r=new S.SKPictureRecorder(),rc=r.BeginRecording(S.SKRect.Create(10,10));rc.DrawRect(0,0,10,10,p);const pic=r.EndRecording();try{c.DrawPicture(pic,new S.SKPoint(60,30));assert.deepEqual(pixel(s,62,32),[255,0,0,255]);c.DrawPicture(pic,80,40);assert.deepEqual(pixel(s,82,42),[255,0,0,255]);}finally{pic.Dispose();r.Dispose();}c.DrawColor(new S.SKColor(0,0,255,128));assert.deepEqual(pixel(s,0,0),[0,0,255,128]);}finally{p.Dispose();s.Dispose();}
});
test('lattice supports fixed borders, stretched cells, transparent and fixed-color cells',()=>{
 const source=new S.SKBitmap(6,6),p=new S.SKPaint({Color:S.SKColors.Red}),s=surface();source.Erase(S.SKColors.Red);for(let y=2;y<4;y++)for(let x=2;x<4;x++)source.SetPixel(x,y,S.SKColors.Blue);const image=S.SKImage.FromBitmap(source);try{const c=s.Canvas;c.Clear(S.SKColors.White);c.DrawImageLattice(image,[2,4],[2,4],S.SKRect.Create(10,10,60,40));assert.deepEqual(pixel(s,10,10),[255,0,0,255]);assert.deepEqual(pixel(s,15,15),[0,0,255,255]);assert.deepEqual(pixel(s,68,48),[255,0,0,255]);const types=Array(9).fill(0);types[0]=S.SKLatticeRectType.Transparent;types[4]=S.SKLatticeRectType.FixedColor;const lattice=new S.SKLattice([2,4],[2,4],types,null,Array(9).fill(S.SKColors.Lime));c.DrawImageLattice(image,lattice,S.SKRect.Create(80,10,60,40));assert.deepEqual(pixel(s,80,10),[255,255,255,255]);assert.deepEqual(pixel(s,90,20),[0,255,0,255]);assert.throws(()=>c.DrawImageLattice(image,[4,2],[2,4],S.SKRect.Create(20,20)),/sorted/);c.DrawBitmapNinePatch(source,new S.SKRectI(2,2,4,4),S.SKRect.Create(10,60,60,40),K.FilterMode.Nearest,p);assert.deepEqual(pixel(s,20,70),[0,0,255,255]);}finally{source.Dispose();image.Dispose();p.Dispose();s.Dispose();}
});
test('font encoding, output buffers, positions, text widths, paint delegates and metrics match native glyph data',()=>{
 const f=new S.SKFont(null,24),p=new S.SKPaint(f);try{const text='AΩ🙂',u8=new TextEncoder().encode(text),u16=new Uint8Array(text.length*2),dv=new DataView(u16.buffer);for(let i=0;i<text.length;i++)dv.setUint16(i*2,text.charCodeAt(i),true);const expected=f.GetGlyphs(text),out=new Uint16Array(3);f.GetGlyphs(u16,S.SKTextEncoding.Utf16,out);assert.deepEqual(out,expected);assert.deepEqual(f.GetGlyphs(u8,S.SKTextEncoding.Utf8),expected);assert.equal(f.CountGlyphs(u16,S.SKTextEncoding.Utf16),3);assert.equal(f.GetGlyph(65),expected[0]);const widths=new Float32Array(3),bounds=[];f.GetGlyphWidths(text,widths,bounds,p);assert.equal(bounds.length,3);close(f.MeasureText(text),widths.reduce((a,b)=>a+b,0));const positions=[];f.GetGlyphPositions(u8,S.SKTextEncoding.Utf8,positions,new S.SKPoint(5,8));assert.equal(positions[0].X,5);assert.equal(positions[1].Y,8);close(positions[1].X,5+widths[0]);const offsets=new Float32Array(3);f.GetGlyphOffsets(expected,offsets,4);close(offsets[1],4+widths[0]);assert.deepEqual(p.GetGlyphWidths('ABC'),f.GetGlyphWidths('ABC'));p.TextEncoding=S.SKTextEncoding.Utf16;close(p.MeasureText(u16),f.MeasureText(text));const metrics={};close(f.GetFontMetrics(metrics),f.Spacing);assert.ok(metrics.Ascent<0);const br={};assert.equal(f.BreakText('ABC',f.MeasureText('AB')+.1,br),2);assert.equal(br.Text,'AB');}finally{p.Dispose();f.Dispose();}
});
test('text path positions and text-on-path draw actual outlines with straight and warped placement',()=>{
 const f=new S.SKFont(null,30),p=new S.SKPaint({Color:S.SKColors.Black,IsAntialias:true}),path=new S.SKPath(),s=surface();path.MoveTo(10,70).CubicTo(40,10,100,110,150,35);try{const letters=f.GetGlyphs('ABC'),positions=[new S.SKPoint(10,50),new S.SKPoint(50,50),new S.SKPoint(90,50)],outline=f.GetTextPath('ABC',positions);assert.ok(outline.Bounds.Left>=10&&outline.Bounds.Right>90);outline.Dispose();const warped=f.GetTextPathOnPath('ABC',path);assert.ok(warped.PointCount>10);assert.ok(warped.IsFinite);warped.Dispose();s.Canvas.Clear(S.SKColors.White);s.Canvas.DrawTextOnPath('ABC',path,new S.SKPoint(),true,K.TextAlign.Center,f,p);assert.ok(pixel(s,0,0)[0]===255);const img=s.Snapshot();try{assert.ok(img.ReadPixels().some((v,i)=>i%4!==3&&v<100),'text must alter image pixels');}finally{img.Dispose();}s.Canvas.DrawPositionedText('ABC',positions,f,p);s.Canvas.DrawTextOnPath('DEF',path,0,20,f,p);}finally{s.Dispose();f.Dispose();p.Dispose();path.Dispose();}
});
test('stroke fill geometry and fast bounds contain rendered strokes',()=>{
 const path=new S.SKPath().MoveTo(10,20).LineTo(100,20),p=new S.SKPaint({Style:K.PaintStyle.Stroke,StrokeWidth:10,StrokeCap:K.StrokeCap.Round});try{const filled=p.GetFillPath(path);try{assert.ok(filled.Contains(10,20));assert.ok(filled.Bounds.Top<=15);const dst=new S.SKPath();try{assert.equal(p.GetFillPath(path,dst),true);assert.ok(dst.Equals(filled));}finally{dst.Dispose();}const b={};assert.equal(p.GetFastBounds(path.Bounds,b),true);assert.ok(b.Top<=filled.Bounds.Top);}finally{filled.Dispose();}}finally{path.Dispose();p.Dispose();}
});
test('save-layer record applies actual opacity and clip, vertices overload renders',()=>{
 const s=surface(),p=new S.SKPaint({Color:new S.SKColor(0,0,0,128)}),red=new S.SKPaint({Color:S.SKColors.Red});try{const c=s.Canvas;c.Clear(S.SKColors.White);const count=c.SaveLayer(new S.SKCanvasSaveLayerRec(S.SKRect.Create(160,120),p));c.DrawRect(0,0,100,100,red);c.RestoreToCount(count);assert.ok(pixel(s,10,10)[1]>=126&&pixel(s,10,10)[1]<=128);red.Color=S.SKColors.White;c.DrawVertices(K.VertexMode.Triangles,[new S.SKPoint(100,10),new S.SKPoint(150,10),new S.SKPoint(150,70)],[S.SKColors.Blue,S.SKColors.Blue,S.SKColors.Blue],red);assert.deepEqual(pixel(s,140,20),[0,0,255,255]);}finally{s.Dispose();p.Dispose();red.Dispose();}
});

test('value constructor overloads and padded pixel destinations preserve row strides',()=>{
 const size=new S.SKSize(new S.SKPoint(20,30)),sizei=new S.SKSizeI(new S.SKPointI(4,6)),pt=new S.SKPointI(sizei);assert.deepEqual(size.ToArray(),[20,30]);assert.deepEqual(pt.ToArray(),[4,6]);assert.deepEqual(S.SKRect.Create(pt,size).ToArray(),[4,6,24,36]);assert.deepEqual(S.SKPoint.Reflect(new S.SKPoint(1,-2),new S.SKPoint(0,1)).ToArray(),[1,-12]);
 const s=surface();try{s.Canvas.Clear(S.SKColors.Red);const info=new S.SKImageInfo(2,2),dst=new Uint8Array(24).fill(99);assert.equal(s.Canvas.ReadPixels(info,dst,12,0,0),true);assert.deepEqual(Array.from(dst.slice(0,8)),[255,0,0,255,255,0,0,255]);assert.deepEqual(Array.from(dst.slice(8,12)),[99,99,99,99]);assert.deepEqual(Array.from(dst.slice(12,20)),[255,0,0,255,255,0,0,255]);const p=new S.SKPixmap(info,new Uint8Array(16));try{assert.equal(s.Canvas.ReadPixels(p,0,0),true);assert.equal(p.GetPixels()[0],255);}finally{p.Dispose();}const all=s.ReadPixels();assert.equal(all.length,s.Width*s.Height*4);}finally{s.Dispose();}
});

test('pinned .NET matrix storage, banker rounding, checked conversion and degenerate rectangles',()=>{
 assert.deepEqual(new S.SKMatrix44().Values,Array(16).fill(0));assert.ok(S.SKMatrix44.CreateIdentity().IsIdentity);const t=S.SKMatrix44.CreateTranslation(7,9,11);assert.equal(t.M30,7);assert.deepEqual(t.MapPoint(1,2,3).ToArray(),[8,11,14]);assert.deepEqual(t.Matrix.MapPoint(1,2).ToArray(),[8,11]);assert.deepEqual(new S.SKMatrix44(S.SKMatrix.CreateTranslation(7,9)).MapPoint(1,2).ToArray(),[8,11]);const s=surface(),p=new S.SKPaint({Color:S.SKColors.Red});try{s.Canvas.Clear(S.SKColors.White);s.Canvas.Concat(t);s.Canvas.DrawRect(0,0,10,10,p);assert.deepEqual(pixel(s,8,10),[255,0,0,255]);assert.equal(s.Canvas.TotalMatrix44.M30,7);}finally{p.Dispose();s.Dispose();}
 assert.deepEqual(S.SKPointI.Round(new S.SKPoint(2.5,-1.5)).ToArray(),[2,-2]);assert.deepEqual(S.SKRectI.Round(new S.SKRect(.5,1.5,2.5,3.5)).ToArray(),[0,2,2,4]);assert.throws(()=>S.SKPointI.Ceiling(new S.SKPoint(Infinity,0)),/Int32/);assert.deepEqual(S.SKRectI.Ceiling(new S.SKRect(5.2,6.7,1.2,2.3),true).ToArray(),[6,7,1,2]);assert.deepEqual(S.SKRectI.Floor(new S.SKRect(5.2,6.7,1.2,2.3),true).ToArray(),[5,6,2,3]);assert.deepEqual(S.SKRect.Union(S.SKRect.Empty,new S.SKRect(5,5,10,10)).ToArray(),[0,0,10,10]);assert.deepEqual(S.SKRect.Intersect(new S.SKRect(1,1,2,2),new S.SKRect(2,1,4,4)).ToArray(),[2,1,2,2]);
});

test('pinned rectangle emptiness and all rounded-rectangle contour start indices',()=>{
 assert.equal(new S.SKRect(5,5,5,5).IsEmpty,false);assert.equal(S.SKRect.Empty.IsEmpty,true);assert.equal(new S.SKRectI(5,5,3,3).IsEmpty,false);
 const rr=new S.SKRoundRect(new S.SKRect(10,20,110,80));rr.SetRectRadii(rr.Rect,[new S.SKPoint(10,20),new S.SKPoint(15,25),new S.SKPoint(20,10),new S.SKPoint(5,15)]);const expected=[[20,20],[95,20],[110,45],[110,70],[90,80],[15,80],[10,65],[10,40]],surfaces=[];try{for(const direction of [0,1])for(let index=0;index<8;index++){const path=new S.SKPath().AddRoundRect(rr,direction,index),s=surface(),paint=new S.SKPaint({Color:S.SKColors.Red});try{assert.deepEqual(path.GetPoint(0).ToArray(),expected[index]);assert.equal(path.Contains(50,50),true);assert.equal(path.Contains(10,20),false);assert.deepEqual(path.Bounds.ToArray(),rr.Rect.ToArray());s.Canvas.Clear(S.SKColors.White);s.Canvas.DrawPath(path,paint);const image=s.Snapshot();try{surfaces.push(image.ReadPixels());}finally{image.Dispose();}}finally{paint.Dispose();path.Dispose();s.Dispose();}}for(const pixels of surfaces.slice(1))assert.deepEqual(pixels,surfaces[0]);}finally{}
});
