import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {Initialize} from '../dist/lib/index.js';
import {createRegionEffectScenes} from '../dist/region-effect-scenes.js';
import {installLayerEffects} from '../dist/lib/layer-effects.js';
const require=createRequire(import.meta.url),K=await require('../dist/vendor/canvaskit.cjs')({wasmBinary:readFileSync(new URL('../dist/vendor/canvaskit.wasm',import.meta.url))});
const S=await Initialize({CanvasKit:K,isolated:true,fonts:[{data:readFileSync(new URL('../dist/fonts/DejaVuSans.ttf',import.meta.url)),family:'DejaVu Sans'}]});installLayerEffects(K,S);
for(const scene of createRegionEffectScenes(S)){const surface=S.SKSurface.Create(new S.SKImageInfo(960,600));try{scene.draw(surface.Canvas,960,600,{time:1,amount:10});const image=surface.Snapshot(),data=image.Encode(S.SKEncodedImageFormat.Png,100);assert(data.Size>3000);console.log('PASS gallery '+scene.id+' '+data.Size+' bytes');data.Dispose();image.Dispose();}finally{surface.Dispose();}}
const surface=S.SKSurface.Create(new S.SKImageInfo(400,100)),paint=new S.SKPaint({Color:S.SKColors.Red,ColorFilter:S.SKColorFilter.CreateTable(null,Array.from({length:256},(_,i)=>255-i),null,null)}),font=new S.SKFont(null,40);surface.Canvas.Clear(S.SKColors.White);surface.Canvas.DrawShapedText('office سلام',10,55,font,paint);const snapshot=surface.Snapshot(),pixels=snapshot.ReadPixels(new S.SKImageInfo(400,100,S.SKColorType.Rgba8888,S.SKAlphaType.Unpremul)),black=Array.from({length:400*100},(_,i)=>pixels[i*4]<80&&pixels[i*4+1]<80&&pixels[i*4+2]<80).filter(Boolean).length;assert(black>100,'Shaped software-filter text must become black');console.log('PASS shaped text software color filter '+black+' black pixels');snapshot.Dispose();font.Dispose();paint.Dispose();surface.Dispose();
{
  const source=S.SKSurface.Create(new S.SKImageInfo(4,4));source.Canvas.Clear(S.SKColors.Red);const image=source.Snapshot(),destination=S.SKSurface.Create(new S.SKImageInfo(20,20)),invert=Array.from({length:256},(_,i)=>255-i),filter=S.SKColorFilter.CreateTable(null,invert,invert,invert),p=new S.SKPaint({ColorFilter:filter});destination.Canvas.Clear(S.SKColors.Blue);destination.Canvas.DrawImage(image,5,5,p);const data=destination.Canvas.ReadPixels(new S.SKImageInfo(20,20,S.SKColorType.Rgba8888,S.SKAlphaType.Unpremul));assert.deepEqual(Array.from(data.slice((6*20+6)*4,(6*20+6)*4+4)),[0,255,255,255]);assert.deepEqual(Array.from(data.slice(0,4)),[0,0,255,255]);[source,image,destination,filter,p].forEach(x=>x.Dispose());console.log('PASS public scalar DrawImage software table filter');
}
{
  const surface=S.SKSurface.Create(new S.SKImageInfo(100,20)),path=new S.SKPath().MoveTo(0,10).LineTo(100,10),effect=S.SKPathEffect.CreateTrim(.2,.6),p=new S.SKPaint({Color:S.SKColors.Red,Style:S.SKPaintStyle.Stroke,StrokeWidth:4,PathEffect:effect});surface.Canvas.Clear(S.SKColors.Blue);surface.Canvas.DrawPath(path,p);const data=surface.Canvas.ReadPixels(new S.SKImageInfo(100,20,S.SKColorType.Rgba8888,S.SKAlphaType.Unpremul)),pixel=x=>Array.from(data.slice((10*100+x)*4,(10*100+x)*4+4));assert.deepEqual(pixel(10),[0,0,255,255]);assert.deepEqual(pixel(30),[255,0,0,255]);assert.deepEqual(pixel(80),[0,0,255,255]);[surface,path,effect,p].forEach(x=>x.Dispose());console.log('PASS public DrawPath software trim geometry');
}
